create database projects;
use projects;
select * from hr;

alter table hr 
change column ï»¿id emp_id varchar(20) null;

select * from hr;

describe hr;

select birthdate from hr;

set sql_safe_updates=0;


update hr 
set birthdate=case 
when birthdate like '%/%' then date_format(str_to_date(birthdate,'%m/%d/%Y'),'%Y-%m-%d')
when birthdate like '%-%' then date_format(str_to_date(birthdate,'%m-%d-%Y'),'%Y-%m-%d')
else null
end;

alter table hr
modify column birthdate date;


select * from hr;

describe hr;

update hr
set hire_date=case
when hire_date like '%/%' then date_format(str_to_date(hire_date,'%m/%d/%Y'),'%Y-%m-%d')
when hire_date like '%-%' then date_format(str_to_date(hire_date,'%m-%d-%Y'),'%Y-%m-%d')
else null
end;


ALTER TABLE HR MODIFY COLUMN hire_date DATE;

ALTER TABLE HR ADD AGE int;

SELECT TERMDATE FROM HR;

UPDATE hr
SET termdate = IF(termdate IS NOT NULL AND termdate != '', date(str_to_date(termdate, '%Y-%m-%d %H:%i:%s UTC')), '0000-00-00')
WHERE true;



SELECT termdate from hr;

SET sql_mode = 'ALLOW_INVALID_DATES';

ALTER TABLE hr
MODIFY COLUMN termdate DATE;

UPDATE HR
SET AGE=timestampdiff(YEAR,BIRTHDATE,CURDATE());

SELECT * FROM HR;

SELECT MIN(AGE) AS YOUNGEST,
       MAX(AGE) AS OLDEST FROM HR;

SELECT COUNT(*) FROM HR WHERE AGE<18;

-- ============================================================
-- QUESTIONS

-- 1)WHAT IS THE GENDER BREAKDOWN OF EMPLOYESS IN THE COMPANY

SELECT GENDER,COUNT(*) AS COUNT FROM HR 
WHERE AGE>=18 AND TERMDATE='0000-00-00' 
GROUP BY GENDER;

-- 2)WHAT IS THE RACE/ETHNICITY BREAKDOWN OF EMPLOYESS IN THE COMPANY?


SELECT RACE,COUNT(*) AS COUNT FROM HR
WHERE AGE>=18 AND TERMDATE='0000-00-00'
GROUP BY RACE
ORDER BY COUNT(*) DESC;

-- 3)WHAT IS THE AGE DISTRIBUTION OF EMPLOYESS IN THE COMPANY?

SELECT MIN(AGE) AS  YOUNGEST,
       MAX(AGE) AS OLDEST
       FROM HR
       WHERE AGE>=18 AND TERMDATE='0000-00-00';
	
-- SELECT CASE 
-- WHEN AGE>=18 AND AGE<=24 THEN '18-24'
-- WHEN AGE>=25 AND AGE<=34 THEN '25-34'
-- WHEN AGE>=35 AND AGE<=44 THEN '35-44'
-- WHEN AGE>=45 AND AGE<=54 THEN '45-54'
-- WHEN AGE>=55 AND AGE<=64 THEN '55-64'
-- ELSE '65+'
-- END AS AGE_GROUP,COUNT(*) AS COUNT
-- FROM HR
-- WHERE AGE>=18 AND TERMDATE='0000-00-00'
-- GROUP BY AGE_GROUP
-- ORDER BY AGE_GROUP;

SELECT CASE 
WHEN AGE>=18 AND AGE<=24 THEN '18-24'
WHEN AGE>=25 AND AGE<=34 THEN '25-34'
WHEN AGE>=35 AND AGE<=44 THEN '35-44'
WHEN AGE>=45 AND AGE<=54 THEN '45-54'
WHEN AGE>=55 AND AGE<=64 THEN '55-64'
ELSE '65+'
END AS AGE_GROUP,gender,COUNT(*) AS COUNT
FROM HR
WHERE AGE>=18 AND TERMDATE='0000-00-00'
GROUP BY AGE_GROUP,gender
ORDER BY AGE_GROUP,gender;
SELECT * FROM HR;
-- 4)HOW MANY EMPLOYESS WORK AT HEADQUATERS VERSUS REMOTE LOCATIONS?

SELECT LOCATION,COUNT(*) AS COUNT FROM HR GROUP BY LOCATION ;
    
-- 5)WHAT IS THE AVG LENGTH OF EMPLOYMENT FOR EMPLOYEES WHO ARE BEEN TERMINATED?

-- SELECT datediff(TERMDATE,HIRE_DATE),COUNT(*) AS COUNT FROM HR WHERE TERMDATE <>0 GROUP BY TERMDATE;

SELECT ROUND(AVG(datediff(TERMDATE,HIRE_DATE))/365,0) AS AVG_LENGTH_EMPLOYMENT
 FROM HR 
WHERE TERMDATE <=curdate() AND TERMDATE <>'0000-00-00' AND AGE>=18;

-- 6.HOW DOES THE GENDER DISTRIBUTION VARY ACROSS DEPARTMENTS AND JOB TITLES?
SELECT DEPARTMENT,GENDER,COUNT(*) AS COUNT
FROM HR WHERE AGE>=18 AND TERMDATE='0000-00-00'
GROUP BY DEPARTMENT,GENDER
ORDER BY DEPARTMENT;

-- 7 WHAT IS THE DISTRIBUTION OF JOB TITLES ACROSS THE COMPANY;
SELECT * FROM HR;
SELECT JOBTITLE,COUNT(*) AS COUNT FROM HR
WHERE AGE>=18 AND TERMDATE='0000-00-00'
group by JOBTITLE 
ORDER BY JOBTITLE DESC;

-- 8)WHICH DEPARTMENT HAS THE HIGHEST TURNOVER RATE?
SELECT DEPARTMENT,TOTAL_COUNT,TERMINATED_COUNT,TERMINATED_COUNT/TOTAL_COUNT AS
 TERMINATION_RATE
FROM (
SELECT DEPARTMENT,COUNT(*) AS TOTAL_COUNT,
sum(CASE WHEN TERMDATE <>'0000-00-00'AND TERMDATE<=CURDATE()THEN 1 ELSE 0 END) AS TERMINATED_COUNT
FROM HR WHERE AGE>=18
GROUP BY DEPARTMENT) AS SUBQUERY
ORDER BY TERMINATION_RATE DESC;

-- 9) WHAT IS THE DISTRIBUTION OF EMPLOYES ACROSS LOCATIONS BY CITY AND STATE?
SELECT LOCATION_STATE,count(*) AS COUNT FROM HR
WHERE AGE>=18 AND TERMDATE='0000-00-00'
group by LOCATION_STATE
ORDER BY COUNT DESC;

-- 10)HOW HAS THE COMPANY EMPLOYEE COUNT CHANGED OVERTIME BASED ON HIRE AND TERM DATES?
SELECT 
YEAR,
HIRES,
TERMINATIONS,
HIRES-TERMINATIONS AS NET_CHANGE,
ROUND((HIRES-TERMINATIONS)/HIRES*100,2)AS NET_CHANGE_PERCENT
FROM(
SELECT
YEAR(HIRE_DATE)AS YEAR,
count(*) AS HIRES,
SUM(CASE WHEN TERMDATE<>'0000-00-00' AND TERMDATE <=CURDATE() THEN 1 ELSE 0 END) AS TERMINATIONS
FROM HR
WHERE AGE>=18
GROUP BY YEAR(HIRE_DATE))
AS SUBQUERY
order by YEAR ASC;

-- 11.WHAT IS THE TENURE DISTRIBUTION FOR EACH DEPARTMENT?
SELECT DEPARTMENT,ROUND(AVG(datediff(TERMDATE,HIRE_DATE)/365),0) AS AVG_TENURE
FROM HR
WHERE TERMDATE <=CURDATE() AND TERMDATE<>'0000-00-00' AND AGE>=18
GROUP BY DEPARTMENT;



